# Generated by Django 5.1.5 on 2025-02-07 12:33

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.cell_image_path)),
                ('center_x_in_region', models.FloatField(blank=True, null=True)),
                ('center_y_in_region', models.FloatField(blank=True, null=True)),
                ('TL_x_in_region', models.FloatField(blank=True, null=True)),
                ('TL_y_in_region', models.FloatField(blank=True, null=True)),
                ('BR_x_in_region', models.FloatField(blank=True, null=True)),
                ('BR_y_in_region', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=25)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=core.models.case_video_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CellClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_class', models.CharField(blank=True, max_length=250, null=True)),
                ('user_class', models.CharField(blank=True, max_length=250, null=True)),
                ('blast_score', models.FloatField(blank=True, null=True)),
                ('myelocyte_score', models.FloatField(blank=True, null=True)),
                ('metamyelocyte_score', models.FloatField(blank=True, null=True)),
                ('neutrophil_score', models.FloatField(blank=True, null=True)),
                ('monocyte_score', models.FloatField(blank=True, null=True)),
                ('eosinophil_score', models.FloatField(blank=True, null=True)),
                ('basophil_score', models.FloatField(blank=True, null=True)),
                ('lymphocyte_score', models.FloatField(blank=True, null=True)),
                ('plasma_cell_score', models.FloatField(blank=True, null=True)),
                ('erythroid_precursor_score', models.FloatField(blank=True, null=True)),
                ('skippocyte_score', models.FloatField(blank=True, null=True)),
                ('model_id', models.IntegerField()),
                ('cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifcation', to='core.cell')),
            ],
        ),
        migrations.CreateModel(
            name='CellDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_score', models.FloatField(blank=True, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('is_user_added', models.BooleanField(default=False)),
                ('cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='core.cell')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('TL_x_in_frame', models.FloatField(blank=True, null=True)),
                ('TL_y_in_frame', models.FloatField(blank=True, null=True)),
                ('BR_x_in_frame', models.FloatField(blank=True, null=True)),
                ('BR_y_in_frame', models.FloatField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='core.case')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='core.region'),
        ),
        migrations.CreateModel(
            name='RegionClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_score', models.FloatField(blank=True, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('classifier_id', models.IntegerField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.region_image_path)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='core.region')),
            ],
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='core_case_status_59308c_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['date'], name='core_case_date_7ae9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user'], name='core_case_user_id_9500ea_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['case'], name='core_region_case_id_2fbe68_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['region'], name='core_cell_region__5aa6ab_idx'),
        ),
    ]
