# Generated by Django 5.1.5 on 2025-02-07 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cell',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_cells', to='core.region'),
        ),
        migrations.AlterField(
            model_name='cellclassification',
            name='cell',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_classifcation', to='core.cell'),
        ),
        migrations.AlterField(
            model_name='celldetection',
            name='cell',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_detection', to='core.cell'),
        ),
        migrations.AlterField(
            model_name='region',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_regions', to='core.case'),
        ),
        migrations.AlterField(
            model_name='regionclassification',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_classification', to='core.region'),
        ),
        migrations.AlterField(
            model_name='regionimage',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_image', to='core.region'),
        ),
    ]
