# Generated by Django 4.2.19 on 2025-02-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('case_name', models.CharField(blank=True, max_length=255, null=True)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('case_date', models.DateField(blank=True, null=True)),
                ('case_time', models.TimeField(blank=True, null=True)),
                ('case_status', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('video_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('TL_x', models.FloatField(blank=True, null=True)),
                ('TL_y', models.FloatField(blank=True, null=True)),
                ('BR_x', models.FloatField(blank=True, null=True)),
                ('BR_y', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
