# Generated by Django 4.2.19 on 2025-02-10 22:00

import cases.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('case_name', models.CharField(blank=True, max_length=255, null=True)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('case_date', models.DateField(blank=True, null=True)),
                ('case_time', models.TimeField(blank=True, null=True)),
                ('case_status', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('video_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=cases.models.case_video_path)),
                ('azure_url', models.URLField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(db_column='case_id', on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_status'], name='cases_case_st_d9e3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user'], name='cases_user_id_0c478c_idx'),
        ),
    ]
