# Generated by Django 5.1.5 on 2025-02-06 13:31

import cases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='video_file_path',
        ),
        migrations.AddField(
            model_name='case',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=cases.models.case_video_path),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['date'], name='cases_case_date_a8b8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user'], name='cases_case_user_id_524ef7_idx'),
        ),
    ]
