# Generated by Django 4.2.19 on 2025-02-20 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_status'], name='cases_case_st_d9e3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['user'], name='cases_user_id_0c478c_idx'),
        ),
    ]
