# Generated by Django 4.2.19 on 2025-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_date_added_video_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='BR_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='BR_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='TL_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='TL_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
