# Generated by Django 5.1.5 on 2025-02-07 12:56

from django.db import migrations, models

def transfer_video_data(apps, schema_editor):
    Case = apps.get_model('cases', 'Case')
    Video = apps.get_model('cases', 'Video')

    for case in Case.objects.exclude(video_file='').exclude(video_file=None):
        Video.objects.create(case=case, video_file=case.video_file)


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_video_case'),
    ]

    operations = [
        migrations.RunPython(transfer_video_data)
    ]
