# Generated by Django 5.1.5 on 2025-02-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20250207_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='video_file',
        ),
    ]
