# Generated by Django 5.1.5 on 2025-02-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_remove_case_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='azure_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
