# Generated by Django 5.1.5 on 2025-02-06 13:31

import django.db.models.deletion
import regions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_remove_case_video_file_path_case_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('TL_x_in_frame', models.FloatField()),
                ('TL_y_in_frame', models.FloatField()),
                ('BR_x_in_frame', models.FloatField()),
                ('BR_y_in_frame', models.FloatField()),
                ('group_id', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='RegionClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_classification_score', models.FloatField()),
                ('is_selected_by_region_classifier', models.BooleanField(default=False)),
                ('region_classifier_id', models.IntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_image', models.ImageField(blank=True, null=True, upload_to=regions.models.region_image_path)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='regions.region')),
            ],
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['case'], name='regions_reg_case_id_c33d8b_idx'),
        ),
    ]
