# Generated by Django 5.1.5 on 2025-02-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionclassification',
            old_name='region_classification_score',
            new_name='classification_score',
        ),
        migrations.RenameField(
            model_name='regionclassification',
            old_name='region_classifier_id',
            new_name='classifier_id',
        ),
        migrations.RenameField(
            model_name='regionclassification',
            old_name='is_selected_by_region_classifier',
            new_name='is_selected',
        ),
        migrations.RenameField(
            model_name='regionimage',
            old_name='region_image',
            new_name='image',
        ),
    ]
