# Generated by Django 4.2.19 on 2025-02-16 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
