# Generated by Django 5.1.5 on 2025-02-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_rename_region_classification_score_regionclassification_classification_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='BR_x_in_frame',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='BR_y_in_frame',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='TL_x_in_frame',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='TL_y_in_frame',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regionclassification',
            name='classification_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regionclassification',
            name='classifier_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
