# Generated by Django 5.1.5 on 2025-02-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_date_added_video'),
        ('regions', '0003_alter_region_br_x_in_frame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='cases.video'),
        ),
    ]
