# Generated by Django 5.1.4 on 2025-02-08 18:49

from django.db import migrations, models

def convert_classifier_ids_to_char(apps, schema_editor):
    RegionClassification = apps.get_model('regions', 'RegionClassification')

    for classification in RegionClassification.objects.all():
        if classification.classifier_id is not None:
            classification.classifier_id = str(classification.classifier_id)
            classification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_region_video'),
    ]

    operations = [
        migrations.RunPython(
            convert_classifier_ids_to_char,
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='regionclassification',
            name='classifier_id',
            field=models.CharField(blank=True, max_length=100, null=True)
        ),
    ]
