# Generated by Django 5.1.5 on 2025-02-06 13:31

import cells.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_image', models.ImageField(blank=True, null=True, upload_to=cells.models.cell_image_path)),
                ('center_x_in_region', models.FloatField()),
                ('center_y_in_region', models.FloatField()),
                ('TL_x_in_region', models.FloatField()),
                ('TL_y_in_region', models.FloatField()),
                ('BR_x_in_region', models.FloatField()),
                ('BR_y_in_region', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='CellClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_cell_class', models.CharField(blank=True, max_length=250, null=True)),
                ('user_class', models.CharField(blank=True, max_length=250, null=True)),
                ('myelocyte_score', models.FloatField(blank=True, null=True)),
                ('metamyelocyte_score', models.FloatField(blank=True, null=True)),
                ('neutrophil_score', models.FloatField(blank=True, null=True)),
                ('monocyte_score', models.FloatField(blank=True, null=True)),
                ('eosinophil_score', models.FloatField(blank=True, null=True)),
                ('erythroid_precursor_score', models.FloatField(blank=True, null=True)),
                ('lymphocyte_score', models.FloatField(blank=True, null=True)),
                ('plasma_cell_score', models.FloatField(blank=True, null=True)),
                ('blast_and_blast_like_score', models.FloatField(blank=True, null=True)),
                ('skippocyte_score', models.FloatField(blank=True, null=True)),
                ('cell_classification_model', models.IntegerField()),
                ('cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifcation', to='cells.cell')),
            ],
        ),
        migrations.CreateModel(
            name='CellDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_detection_score', models.FloatField()),
                ('cell_detection_model_id', models.IntegerField()),
                ('is_user_added', models.BooleanField(default=False)),
                ('cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='cells.cell')),
            ],
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['region'], name='cells_cell_region__604b74_idx'),
        ),
    ]
