# Generated by Django 5.1.5 on 2025-02-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cellclassification',
            old_name='ai_cell_class',
            new_name='ai_class',
        ),
    ]
