# Generated by Django 4.2.19 on 2025-02-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='cell_id',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
