# Generated by Django 5.1.5 on 2025-02-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0002_rename_ai_cell_class_cellclassification_ai_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='cell_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cellclassification',
            old_name='cell_classification_model',
            new_name='model_id',
        ),
        migrations.RenameField(
            model_name='celldetection',
            old_name='cell_detection_score',
            new_name='detection_score',
        ),
        migrations.RenameField(
            model_name='celldetection',
            old_name='cell_detection_model_id',
            new_name='model_id',
        ),
    ]
