# Generated by Django 4.2.19 on 2025-02-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0003_cell_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='date_added',
        ),
    ]
