# Generated by Django 4.2.19 on 2025-02-17 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0004_remove_cell_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
