# Generated by Django 5.1.5 on 2025-02-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0004_alter_cell_br_x_in_region_alter_cell_br_y_in_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellclassification',
            name='basophil_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellclassification',
            name='blast_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
