# Generated by Django 5.1.5 on 2025-02-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0006_remove_cellclassification_blast_and_blast_like_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celldetection',
            name='cell',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='cells.cell'),
        ),
    ]
