# Generated by Django 5.1.4 on 2025-02-08 18:40

from django.db import migrations, models

def convert_model_ids_to_char(apps, schema_editor):
    CellDetection = apps.get_model('cells', 'CellDetection')
    CellClassification = apps.get_model('cells', 'CellClassification')
    
    # Convert CellDetection model_ids
    for detection in CellDetection.objects.all():
        if detection.model_id is not None:
            detection.model_id = str(detection.model_id)
            detection.save()
    
    # Convert CellClassification model_ids
    for classification in CellClassification.objects.all():
        if classification.model_id is not None:
            classification.model_id = str(classification.model_id)
            classification.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0009_alter_cellclassification_model_id'),
    ]

    operations = [
        migrations.RunPython(
            convert_model_ids_to_char,
            migrations.RunPython.noop
        ), 
        migrations.AlterField(
            model_name='celldetection',
            name='model_id',
            field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(
            model_name='cellclassification',
            name='model_id',
            field=models.CharField(blank=True, max_length=100, null=True)
        ),
    ]
